micronaut:
  application:
    name: demo12
  server:
    cors:
      enabled: true

datasources:
  default:
    url: jdbc:mysql://localhost:3306/user_management?ssl=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: update
    entity-scan:
      classpath: true
      packages: 'com.example'

security:
  authentication: bearer
  token:
    jwt:
      signatures:
        secret:
          generator:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:tranthanhhieuthao}"'
